import { inter } from "@/app/ui/fonst";
import "@/app/ui/global.css";
export const metadata = {
  title: "Wellcome to my Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
